version: "3.9"
networks:
  tasknetwork:
    driver: bridge
services:
  mysqlservices:
    image: mysql
    container_name: mysqlcontainer
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - tasknetwork
  mongoservice:
    image: mongo
    container_name: mongocontainer
    ports:
      - 27018:27017
    networks:
      - tasknetwork
  rabbitmqservice:
    image: rabbitmq:management
    container_name: rabbitmqcontainer
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - tasknetwork
  eurekaserverservice:
    container_name: eurekaserver
    build: EurekaServer/
    networks:
      - tasknetwork
    ports:
      - 8761:8761
  eurekaapigatewayservice:
    container_name: eurekaGatewayClient
    build: ApiGateway/
    networks:
      - tasknetwork
    ports:
      - 8086:8086
    depends_on:
      - eurekaserverservice
    restart: always
  userauthservice:
    container_name: eurekaAuthClient
    build: UserService/
    networks:
      - tasknetwork
    ports:
      - 8084:8084
    depends_on:
      - eurekaserverservice
      - eurekaapigatewayservice
      - mysqlservices
    restart: always
  usertodoservice:
    container_name: eurekaToDoClient
    build: ToDoService/
    networks:
      - tasknetwork
    ports:
      - 8098:8098
    depends_on:
      - eurekaserverservice
      - eurekaapigatewayservice
      - mongoservice
      - userauthservice
      - rabbitmqservice
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: rabbitmqcontainer
  userarchieveservice:
    container_name: archiveserverclient
    networks:
      - tasknetwork
    build: ArchiveService/
    ports:
      - 8085:8085
    depends_on:
      - eurekaserverservice
      - eurekaapigatewayservice
      - mongoservice
      - rabbitmqservice
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: rabbitmqcontainer






